export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpg",
        username: "MAC",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpg",
        username: "Mark",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpg",
        username: "Devil",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpg",
        username: "Carter",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpg",
        username: "Parker",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpg",
        username: "Steve",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpg",
        username: "Sundar",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpg",
        username: "Ducky",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpg",
        username: "Peter",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "Love you Friends",
        photo: "assets/post/2.jpg",
        date: "5 mins ago",
        userId: 2,
        like: 71,
        comment: 81,
    },
    {
        id: 3,
        desc: "Friends forever...",
        photo: "assets/post/3.png",
        date: "5 mins ago",
        userId: 3,
        like: 5,
        comment: 21,
    },
    {
        id: 4,
        desc: "Spent a day with beauty...",
        photo: "assets/post/4.jpg",
        date: "5 mins ago",
        userId: 4,
        like: 11,
        comment: 6,
    },
    {
        id: 5,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/5.png",
        date: "5 mins ago",
        userId: 5,
        like: 21,
        comment: 9,
    },
    {
        id: 6,
        photo: "assets/post/6.png",
        date: "5 mins ago",
        userId: 6,
        like: 13,
        comment: 0,
    },
    {
        id: 7,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/7.jpg",
        date: "5 mins ago",
        userId: 7,
        like: 43,
        comment: 8,
    },
    {
        id: 8,
        photo: "assets/post/8.jpg",
        date: "5 mins ago",
        userId: 8,
        like: 13,
        comment: 52,
    },
    {
        id: 9,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/9.jpg",
        date: "5 mins ago",
        userId: 9,
        like: 27,
        comment: 4,
    },
    {
        id: 10,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/10.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 39,
        comment: 9,
    },
    {
        id: 11,
        photo: "assets/post/11.jpg",
        date: "5 mins ago",
        userId: 2,
        like: 7,
        comment: 7,
    },
    {
        id: 12,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/12.jpg",
        date: "5 mins ago",
        userId: 3,
        like: 3,
        comment: 0,
    },
    {
        id: 13,
        photo: "assets/post/13.jpg",
        date: "5 mins ago",
        userId: 4,
        like: 45,
        comment: 7,
    },
    {
        id: 14,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/14.png",
        date: "5 mins ago",
        userId: 5,
        like: 34,
        comment: 5,
    },
    {
        id: 15,
        desc: "Hey..! It's my first post.",
        photo: "assets/post/15.jpg",
        date: "5 mins ago",
        userId: 6,
        like: 12,
        comment: 19,
    },
]